# Generated by Django 5.0.6 on 2025-12-04 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ladākh', 'Ladākh'), ('Lakshadweep', 'Lakshadweep'), ('Mahārāshtra', 'Mahārāshtra'), ('Meghālaya', 'Meghālaya'), ('Manipur', 'Manipur'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Mizoram', 'Mizoram'), ('Arunāchal Pradesh', 'Arunāchal Pradesh'), ('Nāgāland', 'Nāgāland'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Bihār', 'Bihār'), ('Punjab', 'Punjab'), ('Chhattīsgarh', 'Chhattīsgarh'), ('Puducherry', 'Puducherry'), ('Chandīgarh', 'Chandīgarh'), ('Rājasthān', 'Rājasthān'), ('Dādra and Nagar Haveli and Damān and Diu', 'Dādra and Nagar Haveli and Damān and Diu'), ('Sikkim', 'Sikkim'), ('Delhi', 'Delhi'), ('Tamil Nādu', 'Tamil Nādu'), ('Goa', 'Goa'), ('Tripura', 'Tripura'), ('Gujarāt', 'Gujarāt'), ('Telangāna', 'Telangāna'), ('Himāchal Pradesh', 'Himāchal Pradesh'), ('Uttarākhand', 'Uttarākhand'), ('Haryāna', 'Haryāna'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Jhārkhand', 'Jhārkhand'), ('West Bengal', 'West Bengal'), ('Jammu and Kashmīr', 'Jammu and Kashmīr'), ('Karnātaka', 'Karnātaka'), ('Kerala', 'Kerala')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('mobile_prepaid', 'Mobile Prepaid'), ('mobile_postpaid', 'Mobile Postpaid'), ('dth', 'DTH'), ('cable_tv', 'Cable TV'), ('fastag', 'FasTag'), ('electricity_bill', 'ELECTRICITY_BILL')], max_length=50)),
                ('rechargers_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refrence', models.CharField(blank=True, max_length=55, null=True)),
                ('orderid', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('user_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('related_state', models.ForeignKey(blank=True, help_text='Optional: Assign service to a specific state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recharge.state')),
            ],
        ),
    ]
