# Generated by Django 4.2.24 on 2025-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
