# Generated by Django 4.2.24 on 2025-09-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_number',
            new_name='mobile',
        ),
    ]
