# Generated by Django 4.2.24 on 2025-09-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_rename_contact_number_contact_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='heard_from',
        ),
    ]
